import { WooProduct, WooCategory } from "@/types/woocommerce";

export const MOCK_CATEGORIES: WooCategory[] = [
  { id: 101, name: "Wedding Invitations", slug: "wedding-invitations" },
  { id: 102, name: "Wax Seal Collection", slug: "wax-seal-collection" },
  { id: 103, name: "Acrylic Luxury", slug: "acrylic-luxury" },
  { id: 104, name: "Minimal Elegance", slug: "minimal-elegance" },
];

export const MOCK_PRODUCTS: WooProduct[] = [
  {
    id: 1,
    name: "Royal Floral Invitation",
    slug: "royal-floral-invitation",
    permalink: "https://example.com/product/royal-floral-invitation",
    date_created: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>A truly majestic invitation featuring lush floral illustrations and premium textured paper. Perfect for an elegant, classic wedding.</p>",
    short_description: "<p>Majestic floral invitation with premium textured paper.</p>",
    sku: "INV-RF-001",
    price: "15.00",
    regular_price: "15.00",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 120,
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    categories: [MOCK_CATEGORIES[0]],
    tags: [],
    images: [
      {
        id: 11,
        date_created: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        src: "/product_floral.png",
        name: "Royal Floral Invitation",
        alt: "Royal Floral Invitation Flat Lay",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Paper Type",
        position: 0,
        visible: true,
        variation: false,
        options: ["Textured Cotton", "Handmade Paper"],
      }
    ],
    volume_pricing: [
      { min_quantity: 1, max_quantity: 500, price: "55.00" },
      { min_quantity: 501, max_quantity: 1000, price: "49.00" },
      { min_quantity: 1001, max_quantity: null, price: "39.00" }
    ],
  },
  {
    id: 2,
    name: "Ivory Minimal Suite",
    slug: "ivory-minimal-suite",
    permalink: "https://example.com/product/ivory-minimal-suite",
    date_created: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>Embrace the beauty of simplicity with this ivory minimal suite. Clean typography and a warm white aesthetic define this luxury stationery.</p>",
    short_description: "<p>Clean typography and a warm white aesthetic.</p>",
    sku: "INV-IM-002",
    price: "12.00",
    regular_price: "12.00",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 200,
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    categories: [MOCK_CATEGORIES[0], MOCK_CATEGORIES[3]],
    tags: [],
    images: [
      {
        id: 12,
        date_created: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        src: "/product_ivory.png",
        name: "Ivory Minimal Suite",
        alt: "Ivory minimal wedding invitation suite",
      },
    ],
    attributes: [],
    volume_pricing: [
      { min_quantity: 1, max_quantity: 500, price: "45.00" },
      { min_quantity: 501, max_quantity: 1000, price: "39.00" },
      { min_quantity: 1001, max_quantity: null, price: "35.00" }
    ],
  },
  {
    id: 3,
    name: "Acrylic Luxury Set",
    slug: "acrylic-luxury-set",
    permalink: "https://example.com/product/acrylic-luxury-set",
    date_created: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>Make a modern statement with our clear acrylic luxury set. Featuring soft light reflection and cinematic minimalist styling.</p>",
    short_description: "<p>Modern clear acrylic luxury invitation set.</p>",
    sku: "INV-AL-003",
    price: "25.00",
    regular_price: "25.00",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 85,
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    categories: [MOCK_CATEGORIES[0], MOCK_CATEGORIES[2]],
    tags: [],
    images: [
      {
        id: 13,
        date_created: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        src: "/product_acrylic.png",
        name: "Acrylic Luxury Set",
        alt: "Acrylic luxury wedding invitation card",
      },
    ],
    attributes: [
      {
        id: 2,
        name: "Foil Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Gold", "Silver", "Rose Gold"],
      }
    ],
    volume_pricing: [
      { min_quantity: 1, max_quantity: 500, price: "85.00" },
      { min_quantity: 501, max_quantity: 1000, price: "79.00" },
      { min_quantity: 1001, max_quantity: null, price: "69.00" }
    ],
  },
  {
    id: 4,
    name: "Emerald Traditional Invite",
    slug: "emerald-traditional-invite",
    permalink: "https://example.com/product/emerald-traditional-invite",
    date_created: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>A rich emerald green invitation featuring gold foil stamping and a custom wax seal. Perfect for a luxury traditional wedding.</p>",
    short_description: "<p>Rich emerald green with gold foil stamping.</p>",
    sku: "INV-ET-004",
    price: "18.00",
    regular_price: "18.00",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 150,
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    categories: [MOCK_CATEGORIES[0], MOCK_CATEGORIES[1]],
    tags: [],
    images: [
      {
        id: 14,
        date_created: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        src: "/product_emerald.png",
        name: "Emerald Traditional Invite",
        alt: "Emerald traditional wedding invite",
      },
    ],
    attributes: [
      {
        id: 3,
        name: "Wax Seal Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Gold", "Bronze", "Emerald"],
      }
    ],
    volume_pricing: [
      { min_quantity: 1, max_quantity: 500, price: "65.00" },
      { min_quantity: 501, max_quantity: 1000, price: "55.00" },
      { min_quantity: 1001, max_quantity: null, price: "49.00" }
    ],
  }
];
